import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation/Navigation";
import localFont from "next/font/local"
import { checkHealth } from "@/kernolio/checkHealth";
import KernolioDown from "@/components/kernolio-down";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const snPro = localFont({
  src: [
    {
      path: '../fonts/SNPro-Regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../fonts/SNPro-Bold.ttf',
      weight: '700',
      style: 'normal'
    },
  ]
})

export const metadata: Metadata = {
  title: "Matthéo Bigorgne - Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let apiDown = false;

  try {
    await checkHealth();
  } catch {
    apiDown = true;
  }

  if(apiDown) {
    return (
      <html lang="en" className={`${snPro.className} h-full antialiased`}>
        <body className="min-h-full flex flex-col items-center justify-center">
          <KernolioDown />
        </body>
      </html>
    );
  }

  return (
    <html lang="en" className={`${snPro.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col items-center">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
