import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation/Navigation";
import localFont from "next/font/local"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const snPro = localFont({
  src: [
    {
      path: '../fonts/SNPro-Regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../fonts/SNPro-Bold.ttf',
      weight: '700',
      style: 'normal'
    },
  ]
})

export const metadata: Metadata = {
  title: "Matthéo Bigorgne - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${snPro.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col items-center">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
